# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://$MOSQUITTO_HOST:1883"]
username="$MOSQUITTO_INTERNAL_USERNAME"
password="$MOSQUITTO_INTERNAL_PASSWORD"

[backend.semtech_udp]
udp_bind="0.0.0.0:1700"